server:
  port: 8081
  servlet:
    context-path: /api


spring:

  #MySQL 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhihuiwen_data
    username: root
    password: 123456

  # 邮箱配置
  mail:
    host: smtp.163.com
    username: zhihuiwen2025@163.com
    password: {{自行填写}}
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          from: zhihuiwen2025@163.com
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

#Redis 数据库配置
  data:
    redis:
      host: localhost       # Redis 服务器地址
      port: 6379            # Redis 端口
      password:             # 如果有密码，填入密码；没有可以留空
      database: 0           # 使用的数据库编号
      timeout: 6000ms       # 连接超时时间
      jedis:
        pool:
          max-active: 8     # 连接池最大连接数
          max-idle: 8       # 连接池中最多空闲的连接数
          min-idle: 0       # 连接池中最少空闲的连接数
          max-wait: -1ms    # 获取连接的最大等待时间，-1 表示无限等待


# 滑块验证码配置
aj:
  captcha:
#    jigsaw: classpath:images/jigsaw
#    pic-click: classpath:images/pic-click
    cache-type: local

    water-mark: "智慧问"
    slip-offset: 5
    aes-status: true
    interference-options: 2
    font-style: 1
    font-size: 25
    history-data-clear-enable: false
    req-frequency-limit-enable: false
    req-get-lock-limit: 5
    req-get-lock-seconds: 360
    req-get-minute-limit: 30
    req-check-minute-limit: 30
    # req-verify-minute-limit: 30 # Uncomment if needed


# 腾讯云对象存储api配置
tencent:
  cos:
    secretId: {{自行填写}}
    secretKey: {{自行填写}}
    region: {{自行填写}}
    bucketName: {{自行填写}}


#JWT令牌相关配置
jwt:
  secret: g77En8R8xoAQNj1i64Z4p1lfgICaBc240S5u-YDJd-8
  expirationTime: 604800000 # 7天有效期


#分页工具配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 开启驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启日志输出



# AI 接口配置
ai:
  url: https://api.siliconflow.cn/v1/chat/completions
  key: {{自行填写}}
#  model: {{自行填写}}
